blueprints/auth.py
from flask import request, Blueprint, render_template, jsonify, redirect, url_for, session
from exts import mongo
from blueprints.forms import RegisterForm, LoginForm, ResetForm
from werkzeug.security import generate_password_hash, check_password_hash


# /auth
bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = {"email": str(email), "username": str(username), "password": generate_password_hash(password)}
            mongo.db.user.insert_one(user)
            return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.register"))

@bp.route("/login", methods=['GET','POST'])
def login():
    if request.method == 'GET':
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = mongo.db.user.find_one({"email": email})
            if not user:
                print("邮箱在数据库中不存在！")
                return redirect(url_for("auth.login"))
            if check_password_hash(user["password"], password):
                # cookie：
                # cookie中不适合存储太多的数据，只适合存储少量的数据
                # cookie一般用来存放登录授权的东西
                # flask中的session，是经过加密后存储在cookie中的
                session['user_id'] = str(user["_id"])
                return redirect("/")
            else:
                print("密码错误！")
                return redirect(url_for("auth.login"))

        else:
            print(form.errors)
            return redirect(url_for("auth.login"))


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")

@bp.route("/reset_password", methods=["GET", "POST"])
def reset_password():
    if request.method == "GET":
        return render_template("reset_password.html")
    else:
        form = ResetForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = mongo.db.user.find_one({"email": email})
            if not user:
                print("邮箱在数据库中不存在！")
                return redirect(url_for("auth.reset_password"))
            else:
                mongo.db.user.update_one({"email": email}, {"$set": {"password": generate_password_hash(password)}})
                return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.reset_password"))

blueprints/qa.py
import re

import pymongo
from bson import ObjectId
from flask import Blueprint, request, render_template
from flask_paginate import Pagination, get_page_parameter

import StringView
from exts import mongo

# /auth
bp = Blueprint("qa", __name__, url_prefix="/")


@bp.route("/")
# 主界面
def index():
    per_page = int(request.args.get('per_page', 10)) # 每一页显示数量
    # 获取当前为第几页
    page = request.args.get(get_page_parameter(), type=int, default=1)
    url_count = mongo.db.acl_bibs.count_documents({})
    # 获取当前页内容查询结果
    results = mongo.db.acl_bibs.find({}).sort([('year', pymongo.DESCENDING), ('month', pymongo.DESCENDING)]).skip((page-1)*per_page).limit(per_page)
    # 处理多余字符
    arr = []
    for result in results:
        arr.append(result)
    arr_result = StringView.StringView(arr)  #数组接收处理完后的结果
    #实行分页
    pagination = Pagination(bs_version=4, page=page, per_page=per_page, total=url_count)
    return render_template("index.html", arrays=arr_result, pagination=pagination)


@bp.route("/search")
# 搜索页面
def search():
    q = request.args.get("q")
    #搜索：正则表达式，返回标题和摘要中带有关键词的文章
    #todo：排序优化
    q1 = re.compile(q, re.I)
    results = mongo.db.acl_bibs.find({"title": {'$regex': q1}, "abstract": {'$regex': q1}}).sort("year", pymongo.DESCENDING).limit(10)
    # 处理多余字符
    arr = []
    for result in results:
        arr.append(result)
    arr_result = StringView.StringView(arr)  # 数组接收处理完后的结果
    return render_template("index.html", arrays=arr_result)


@bp.route("/qa/detail/<qa_id>")
# 单篇论文的详细页面显示
def qa_detail(qa_id):
    details = mongo.db.acl_bibs.find_one({"_id": ObjectId(qa_id)})
    details = StringView.DictView(details) #处理多余字符
    return render_template("detail.html", details=details)


@bp.route("/keyword/detail/")
# 关键词相关论文
def keyword_detail():
    #details = mongo.db.acl_bibs.find({"keyword": keyword_name})
    return render_template("keyword.html")


@bp.route("/method/detail/<method_name>")
#研究方法相关论文
def method_detail(method_name):
    details = mongo.db.acl_bibs.find({"method": method_name})
    return render_template("method.html", method_name=method_name, details=details)

@bp.route("/merics/detail/<merics_name>")
#merics相关论文
def merics_detail(merics_name):
    details = mongo.db.acl_bibs.find({"merics": merics_name})
    return render_template("merics.html", merics_name=merics_name, details=details)

@bp.route("/task/detail/<task_name>")
#研究任务相关论文
def task_detail(task_name):
    details = mongo.db.acl_bibs.find({"task": task_name})
    return render_template("task.html", task_name=task_name, details=details)


@bp.route("/dataset/detail/<dataset_name>")
#数据集相关论文
def dateset_detail(dataset_name):
    details = mongo.db.acl_bibs.find({"dataset": dataset_name})
    return render_template("dataset.html", dataset_name=dataset_name, details=details)

blueprints/reading.py
from flask import Blueprint, request, render_template, redirect, make_response, url_for, send_from_directory
from werkzeug.utils import secure_filename
import os
import config
from pymongo import MongoClient
from gridfs import GridFS



# /auth
bp = Blueprint("reading", __name__, url_prefix="/reading")
#client = MongoClient('mongodb://localhost:27017/')
#db = client['acl_bibs']
#gfs = GridFS(db, collection="pdf")

def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1].lower() in config.ALLOW_EXTENSION


@bp.route("/",methods=['GET','POST'])
def upload():
    global filename
    if request.method == 'POST':
        if 'file' not in request.files:
            print('No file part')
        file = request.files['file']
        if file.filename == '':
            print('No selected file')
        else:
            filename = secure_filename(file.filename)
            #kwargs = {"filename": filename, "content_type": "PDF"}
            #gfs.put(file, **kwargs)
            uploadpath = os.path.join(config.UPLOAD_FOLDER, filename)
            file.save(uploadpath)
        return redirect(url_for('reading.viewer', filename=filename))
    return render_template("literature reading.html")

@bp.route("/viewer/<filename>")
def viewer(filename):
    src = 'http://127.0.0.1:5000/static/pdfjs/web/viewer.html?file=\\static\\uploads\\'+filename
    return render_template("viewer.html", src=src)

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static',filename='bootstrap/bootstrap.4.6.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="/">学术资源分析与推荐</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">首页<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('reading.upload') }}">文献阅读</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">智能问答</a>
                    </li>
                    <li class="nav-item ml-2">
                        <form class="form-inline my-2 my-lg-0" method="GET" action="{{ url_for('qa.search') }}">
                            <input class="form-control mr-sm-2" type="search" placeholder="关键词" aria-label="Search" name="q">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                        </form>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user %}
                        <li class="nav-item">
                            <span class="nav-link">{{ user.username }}</span>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.logout') }}">退出登录</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login') }}">登录</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block body %}{% endblock %}
    </div>
</body>

</html>

templates/dataset.html
{% extends "base.html" %}

{% block title %}数据集详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div>
        <h1>keyword_name</h1>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div>
        <h3>相关文章</h3>
    </div>
    <hr>
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for detail in details %}
                    <li>
                        <div class="question-main">
                            <div class="question-title"><a
                                    href="{{ url_for('qa.qa_detail',qa_id=result.get('_id')) }}">{{ detail.get('title') }}</a>
                            </div>
                            <div class="question-detail">
                                <span class="question-author">{{ detail.get('author') }} </span>
                                •
                                <span class="question-time">{{ detail.get('month') }}  {{ detail.get('year') }} </span>
                            </div>
                            <div class="question-abstract">{{ detail.get('abstract') }}</div>
                            <p>
                                <a href="{{ url_for("qa.keyword_detail", keyword_name=lable) }}">
                                    <span class="badge badge-primary">
                                        <span>{{ lable }}</span>
                                    </span>
                                </a>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/detail.html
{% extends "base.html" %}

{% block title %}结果详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/detail.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
            <div class="col"></div>
            <div class="col-10" style="background-color: #fff;padding: 20px;">
                <h3 class="page-title">{{ details.title }}</h3>
                <p class="question-info">
                    <span>Author：{{ details.author }}</span>
                    <br>
                    <span>Time：{{ details.year }}-{{ details.month }}</span>
                </p>
                <h4>Abstract</h4>
                <hr>
                <p class="question-content">
                    {{ details.abstract }}
                </p>
                <h4>Keywords</h4>
                <hr>
                <p>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>keyword</span>
                        </span>
                    </a>
                </p>
                <p>
                    <h4>Link</h4>
                    <hr>
                    <a href="{{ details.url }}">{{ details.url }} </a>
                </p>
                <p>
                    <h4>Methods</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>methods</span>
                        </span>
                    </a>
                </p>
                <p>
                    <h4>Merics</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>merics</span>
                        </span>
                    </a>
                </p>
                <p>
                    <h4>Tasks</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>tasks</span>
                        </span>
                    </a>
                </p>
                <p>
                    <h4>Datasets</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>Datasets</span>
                        </span>
                    </a>
                </p>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}


{% block title %}首页{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for dict in arrays %}
                    <li>
                        <div class="question-main">
                            <div class="question-title">
                                <a href="{{ url_for('qa.qa_detail',qa_id=dict['_id']) }}">
                                    {{ dict['title'] }}
                                </a>
                            </div>
                            <div class="question-detail">
                                <span class="question-author">{{ dict['author'] }} </span>
                                •
                                <span class="question-time">{{ dict['month'] }}  {{ dict['year'] }} </span>
                            </div>
                            <div class="question-abstract">{{ dict['abstract'] }}</div>
                            <p>
                                <a href="{{ url_for("qa.keyword_detail") }}">
                                    <span class="badge badge-primary">
                                        <span>lable</span>
                                    </span>
                                </a>
                            </p>
                        </div>
                    </li>
                {% endfor %}

            </ul>
        </div>
        <div class="col"></div>
    </div>
    <div style="text-align: center">
        {{ pagination.links }}
    </div>
{% endblock %}


templates/keyword.html
{% extends "base.html" %}

{% block title %}关键词详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div>
        <h1>keyword_name</h1>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div>
        <h3>相关文章</h3>
    </div>
    <hr>
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for detail in details %}
                    <li>
                        <div class="question-main">
                            <div class="question-title"><a
                                    href="{{ url_for('qa.qa_detail',qa_id=result.get('_id')) }}">{{ detail.get('title') }}</a>
                            </div>
                            <div class="question-detail">
                                <span class="question-author">{{ detail.get('author') }} </span>
                                •
                                <span class="question-time">{{ detail.get('month') }}  {{ detail.get('year') }} </span>
                            </div>
                            <div class="question-abstract">{{ detail.get('abstract') }}</div>
                            <p>
                                <a href="{{ url_for("qa.keyword_detail", keyword_name=lable) }}">
                                    <span class="badge badge-primary">
                                        <span>{{ lable }}</span>
                                    </span>
                                </a>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/literature reading.html
{% extends "base.html" %}

{% block title %}文献阅读{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/detail.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10" style="padding-left: 15px;padding-right: 15px;">
            <h2 class="page-title" style="text-align: center;margin-top: 30px;">欢迎使用文献阅读！</h2>
            <object data="{{ url_for('static', filename='images/upload.svg') }}" type="image/svg+xml" style="margin-left: 350px;margin-top:100px;width: 200px;height: 200px;"></object>
            <form action="" method="post" enctype="multipart/form-data">
                <input type="file" name="file" style="margin-left: 270px;margin-top: 100px;">
                <input type="submit" value="上传">
            </form>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block title %}学术资源分析与推荐-登录{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <span>
                            <a href="{{ url_for("auth.reset_password") }}">忘记密码？</a>
                        </span>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">立即登录</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/merics.html
{% extends "base.html" %}

{% block title %}关键词详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div>
        <h1>keyword_name</h1>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div>
        <h3>相关文章</h3>
    </div>
    <hr>
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for detail in details %}
                    <li>
                        <div class="question-main">
                            <div class="question-title"><a
                                    href="{{ url_for('qa.qa_detail',qa_id=result.get('_id')) }}">{{ detail.get('title') }}</a>
                            </div>
                            <div class="question-detail">
                                <span class="question-author">{{ detail.get('author') }} </span>
                                •
                                <span class="question-time">{{ detail.get('month') }}  {{ detail.get('year') }} </span>
                            </div>
                            <div class="question-abstract">{{ detail.get('abstract') }}</div>
                            <p>
                                <a href="{{ url_for("qa.keyword_detail", keyword_name=lable) }}">
                                    <span class="badge badge-primary">
                                        <span>{{ lable }}</span>
                                    </span>
                                </a>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/method.html
{% extends "base.html" %}

{% block title %}方法详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div>
        <h1>method_name</h1>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div>
        <h3>相关文章</h3>
    </div>
    <hr>
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for detail in details %}
                    <li>
                        <div class="question-main">
                            <div class="question-title"><a
                                    href="{{ url_for('qa.qa_detail',qa_id=result.get('_id')) }}">{{ detail.get('title') }}</a>
                            </div>
                            <div class="question-detail">
                                <span class="question-author">{{ detail.get('author') }} </span>
                                •
                                <span class="question-time">{{ detail.get('month') }}  {{ detail.get('year') }} </span>
                            </div>
                            <div class="question-abstract">{{ detail.get('abstract') }}</div>
                            <p>
                                <a href="{{ url_for("qa.keyword_detail", keyword_name=lable) }}">
                                    <span class="badge badge-primary">
                                        <span>{{ lable }}</span>
                                    </span>
                                </a>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}学术资源分析与推荐-注册{% endblock %}

{% block head %}
    <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/register.js') }}"></script>
{% endblock %}

{% block body %}
<div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                        <small id="emailHelp" class="form-text text-muted">我们不会把邮箱用于其他用户</small>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">用户名</label>
                        <input type="text" class="form-control" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">密码</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">确认密码</label>
                        <input type="password" class="form-control" name="password_confirm">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">立即注册</button>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/reset_password.html
{% extends "base.html" %}

{% block title %}学术资源分析与推荐-密码重置{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<div class="row mt-4">
            <div class="col"></div>
            <div class="col">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputEmail1">邮箱</label>
                        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">新密码</label>
                        <input type="password" name="password" class="form-control" id="exampleInputPassword1">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block">确认</button>
                    </div>
                </form>
            </div>
            <div class="col"></div>
        </div>
{% endblock %}

templates/task.html
{% extends "base.html" %}

{% block title %}任务详情{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
{% endblock %}

{% block body %}
    <div>
        <h1>keyword_name</h1>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div>
        <h3>相关文章</h3>
    </div>
    <hr>
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for detail in details %}
                    <li>
                        <div class="question-main">
                            <div class="question-title"><a
                                    href="{{ url_for('qa.qa_detail',qa_id=result.get('_id')) }}">{{ detail.get('title') }}</a>
                            </div>
                            <div class="question-detail">
                                <span class="question-author">{{ detail.get('author') }} </span>
                                •
                                <span class="question-time">{{ detail.get('month') }}  {{ detail.get('year') }} </span>
                            </div>
                            <div class="question-abstract">{{ detail.get('abstract') }}</div>
                            <p>
                                <a href="{{ url_for("qa.keyword_detail", keyword_name=lable) }}">
                                    <span class="badge badge-primary">
                                        <span>{{ lable }}</span>
                                    </span>
                                </a>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/viewer.html
{% extends "base.html" %}

{% block title %}结果{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/detail.css') }}">
{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col-10" >
            <iframe src="{{ src }}" style="width:600px;height:1000px;margin-left: 5px;"></iframe>
        </div>
        <div class="result" style="width: 100px;margin-right: 50px;">
            <h4>Keywords</h4>
            <hr>
            <p>
                <a href="#">
                    <span class="badge badge-primary">
                        <span>keyword</span>
                    </span>
                </a>
            </p>
            <p>
                    <h4>Methods</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>methods</span>
                        </span>
                    </a>
                </p>
                <p>
                    <h4>Merics</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>merics</span>
                        </span>
                    </a>
                </p>
                <p>
                    <h4>Tasks</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>tasks</span>
                        </span>
                    </a>
                </p>
                <p>
                    <h4>Datasets</h4>
                    <hr>
                    <a href="#">
                        <span class="badge badge-primary">
                            <span>Datasets</span>
                        </span>
                    </a>
                </p>
        </div>
    </div>
{% endblock %}